upside down the running condition

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -19,25 +19,28 @@ jobs:
           fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
       - name: Check SHA
         id: check-sha
+        # When there're no SHA changes, step returns 0 (success), but the next steps won't run
+        # When there are, step returns 1 (fail), the job continue-on-error, and the next steps will run
+        continue-on-error: true
         run: |
           LOCAL_DECIDIM_SHA=$(grep revision Gemfile.lock | awk '{print $2}')
           REMOTE_DECIDIM_SHA=$(git ls-remote https://github.com/decidim/decidim.git | grep feature/redesign-staging | awk '{print $1}')
-          [[ $LOCAL_DECIDIM_SHA == $REMOTE_DECIDIM_SHA ]] && { echo "Local and remote Decidim SHA match. Aborting."; exit 1; } || exit 0
+          [[ $LOCAL_DECIDIM_SHA == $REMOTE_DECIDIM_SHA ]] && { echo "Local and remote Decidim SHA match. Aborting."; exit 0; } || exit 1
       - uses: ruby/setup-ruby@v1
-        if: ${{ success() }}
+        if: failure()
         with:
           ruby-version: 3.1.1
       - uses: actions/setup-node@v3
-        if: ${{ success() }}
+        if: failure()
         with:
           node-version: 16.13.0
       - name: Get npm cache directory path
-        if: ${{ success() }}
+        if: failure()
         id: npm-cache-dir-path
         run: echo "::set-output name=dir::$(npm get cache)-decidim-populate-redesign"
         shell: "bash"
       - uses: actions/cache@v3
-        if: ${{ success() }}
+        if: failure()
         id: npm-cache
         with:
           path: ${{ steps.npm-cache-dir-path.outputs.dir }}
@@ -45,18 +48,18 @@ jobs:
           restore-keys: |
             npm-
       - run: ./bin/decidim_auto_update.sh
-        if: ${{ success() }}
+        if: failure()
         name: Run decidim auto update
         shell: "bash"
       - name: Commit & Push changes
-        if: ${{ success() }}
+        if: failure()
         uses: actions-js/push@master
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           author_email: "fernando@populate.tools"
           message: "Update decidim"
       - name: Push to dokku
-        if: ${{ success() }}
+        if: failure()
         uses: dokku/github-action@master
         with:
           # specify the `main` branch as the remote branch to push to
